package com.ed.rules;

import com.usa.ri.gov.bindings.CitizenInfo;
import com.usa.ri.gov.bindings.PlanInfo;

rule "Snap Plan Rules For AP"

	when
		citizenInfo: CitizenInfo(isEmployed=='N')
	then
		PlanInfo planInfo = new PlanInfo();
		planInfo.setPlanName("SNAP");
		planInfo.setPlanStatus("AP");
		planInfo.setPlanStartDate("04-10-2020");
		planInfo.setPlanEndDate("04-12-2020");
		planInfo.setBenefitAmt("$300.00");
		citizenInfo.setPlanInfo(planInfo);
	end

rule "Snap Plan Rules For DN"
	when
		citizenInfo: CitizenInfo(isEmployed=='Y')
	then
		PlanInfo planInfo = new PlanInfo();
		planInfo.setPlanName("SNAP");
		planInfo.setPlanStatus("DN");
		planInfo.setDenialReason("High Income");
		citizenInfo.setPlanInfo(planInfo);
	end